name: flutter_video
description: Samples of video with Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  video_player: ^0.10.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
